name: Validate Docs

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout hornero
      uses: actions/checkout@v2
      with:
        path: hornero
    - name: Build V
      run: |
        make
        sudo ./v symlink
    - name: V doctor
      run: v doctor
    - name: Copy hornero source code to V Modules
      run: cp -rf ./hornero ~/.vmodules
    - name: Validate docs
      run: |
        cd ./hornero
        v check-md .
