name: Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout hornero
      uses: actions/checkout@v2
      with:
        path: hornero
    - name: Build V
      run: |
        make
        sudo ./v symlink
    - name: V doctor
      run: v doctor
    - name: Build docs
      run: |
        rm -f ./hornero/README.md
        mv ./hornero/static/DOCS.md ./hornero/README.md
        v doc -m -f html hornero/
        mv ./hornero/_docs/hornero.html ./hornero/_docs/index.html
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./hornero/_docs/
