name: Periodic Check

on:
  schedule:
    - cron:  '31 1,12 * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout hornero
      uses: actions/checkout@v2
      with:
        path: hornero
    - name: Build V and symlink
      run: |
        make
        sudo ./v symlink
    - name: V doctor
      run: v doctor
    - name: Install hornero and dependencies
      run: |
        sudo apt-get install --quiet -y --no-install-recommends gfortran liblapacke-dev libopenblas-dev
    - name: Move hornero source code to V Modules
      run: mv ./hornero ~/.vmodules
    - name: Execute Tests
      run: ~/.vmodules/hornero/bin/test
